
#development:
#  adapter: redis
#  url: redis://localhost:6379/1


#test:
#  adapter: async

#production:
#  adapter: redis
#  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: auth_system_production

redis: &redis
adapter: redis
url: redis://localhost:6379/1
production: *redis
development: *redis
test: *redis
